# Generated by Django 3.0.6 on 2020-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
